# Generated by Django 4.1.3 on 2022-11-25 01:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/')),
                ('username', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200), size=None)),
            ],
        ),
    ]
