# Generated by Django 4.1.3 on 2022-11-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(default='', max_length=200),
        ),
    ]
