# Generated by Django 4.1.3 on 2022-11-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_age_user_path_to_img_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='path_to_img',
        ),
    ]
